import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import PrivyProviders from "@/providers/privyProvider";
import { ThemeProvider } from "@/providers/themeProvider";
import AppBar from "@/components/AppBar";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sora.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PrivyProviders>
            <AppBar />
            {children}
          </PrivyProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
